### ISSUE TITLE
docker 有问题

### ISSUE THREAD

**Issue by thank243** [Python3WebSpider/ProxyPool#144]
```log
proxypool          | Traceback (most recent call last):
proxypool          |   File "run.py", line 1, in <module>
proxypool          |     from proxypool.scheduler import Scheduler
proxypool          |   File "/app/proxypool/scheduler.py", line 3, in <module>
proxypool          |     from proxypool.processors.server import app
proxypool          |   File "/app/proxypool/processors/server.py", line 1, in <module>
proxypool          |     from flask import Flask, g
proxypool          |   File "/root/.local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
proxypool          |     from . import json
proxypool          |   File "/root/.local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
proxypool          |     from itsdangerous import json as _json
proxypool          | ImportError: cannot import name 'json' from 'itsdangerous' (/root/.local/lib/python3.7/site-packages/itsdangerous/__init__.py)
```
应该是flask的版本问题。

**Comment by Ecalose** [comment]
同

**Comment by LF502** [comment]
一样

**Comment by bigbigmyworld** [comment]
有解决方案了吗

**Comment by LF502** [comment]
requirements.txt 第二行前加上
itsdangerous==0.24

**Comment by xwqsean** [comment]
重新下载镜像吧，作者应该是修复了。我重下就好了

**Comment by thank243** [comment]
> requirements.txt 第二行前加上 itsdangerous==0.24 然后docker删除这个container重新docker-compose up以下 没学过docker但这么做确实有用

因为有这么一句
https://github.com/Python3WebSpider/ProxyPool/blob/23a3b2bce2f328182713bf795632cee93b1403be/Dockerfile#L2

**Comment by xwqsean** [comment]
> > requirements.txt 第二行前加上 itsdangerous==0.24 然后docker删除这个container重新docker-compose up以下 没学过docker但这么做确实有用
> 
> 因为有这么一句
> 
> https://github.com/Python3WebSpider/ProxyPool/blob/23a3b2bce2f328182713bf795632cee93b1403be/Dockerfile#L2

重新拉代码或镜像吧，bug已经被修复了

**Comment by Germey** [comment]
已经修复，感谢大家的提醒！
