### ISSUE TITLE
关于redis-py版本问题

### ISSUE THREAD

**Issue by lyh081** [Python3WebSpider/ProxyPool#20]
redis-py 3.X版和2.X版 zadd和zincrby有变化
3.X版中的zadd需要传入一个dict，（element-names -> score）
zincrby参数中amount和value互换

**Comment by acronema** [comment]
请问下具体怎么修改，源代码还是proxypool部分？

Traceback (most recent call last):
  File "anaconda3/envs/spider/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "anaconda3/envs/spider/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "Code/ProxyPool/proxypool/scheduler.py", line 28, in schedule_getter
    getter.run()
  File "Code/ProxyPool/proxypool/getter.py", line 30, in run
    self.redis.add(proxy)
  File "Code/ProxyPool/proxypool/db.py", line 30, in add
    return self.db.zadd(REDIS_KEY, score, proxy)
  File "naconda3/envs/spider/lib/python3.6/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "anaconda3/envs/spider/lib/python3.6/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'

**Comment by lyh081** [comment]
修改db.py中的 zadd和zincrby函数就可以了，可以参考https://pypi.org/project/redis/中的Upgrading from redis-py 2.X to 3.0部分。
或者可以从我的github仓库clone一份我已经改好的版本，修改的地方有注释。

**Comment by acronema** [comment]
多谢🙏！

**Comment by Germey** [comment]
新版本发布，调整了架构和修复一些问题，欢迎试用和提宝贵意见，谢谢！
