### ISSUE TITLE
项目部署到Linux直接报错了

### ISSUE THREAD

**Issue by jeeshv** [Python3WebSpider/ProxyPool#45]
代理池开始运行
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
代理池开始运行
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local2/app/ProxyPool-master/proxypool/scheduler.py", line 35, in schedule_api
    app.run(API_HOST, API_PORT)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 1009, in run_simple
    inner()
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 962, in inner
    fd=fd,
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/python3/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
代理池开始运行
 * Serving Flask app "proxypool.api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local2/app/ProxyPool-master/proxypool/scheduler.py", line 35, in schedule_api
    app.run(API_HOST, API_PORT)
  File "/usr/local/python3/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 1009, in run_simple
    inner()
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 962, in inner
    fd=fd,
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/python3/lib/python3.6/site-packages/werkzeug/serving.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/python3/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/python3/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
开始抓取代理
获取器开始执行
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 526, in connect
    sock = self._connect()
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 583, in _connect
    raise err
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 571, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local2/app/ProxyPool-master/proxypool/scheduler.py", line 28, in schedule_getter
    getter.run()
  File "/usr/local2/app/ProxyPool-master/proxypool/getter.py", line 23, in run
    if not self.is_over_threshold():
  File "/usr/local2/app/ProxyPool-master/proxypool/getter.py", line 16, in is_over_threshold
    if self.redis.count() >= POOL_UPPER_THRESHOLD:
  File "/usr/local2/app/ProxyPool-master/proxypool/db.py", line 84, in count
    return self.db.zcard(REDIS_KEY)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/client.py", line 2395, in zcard
    return self.execute_command('ZCARD', name)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 1059, in get_connection
    connection.connect()
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 531, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to 120.79.34.216:6379. Connection timed out.
开始抓取代理
获取器开始执行
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 526, in connect
    sock = self._connect()
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 583, in _connect
    raise err
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 571, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local2/app/ProxyPool-master/proxypool/scheduler.py", line 28, in schedule_getter
    getter.run()
  File "/usr/local2/app/ProxyPool-master/proxypool/getter.py", line 23, in run
    if not self.is_over_threshold():
  File "/usr/local2/app/ProxyPool-master/proxypool/getter.py", line 16, in is_over_threshold
    if self.redis.count() >= POOL_UPPER_THRESHOLD:
  File "/usr/local2/app/ProxyPool-master/proxypool/db.py", line 84, in count
    return self.db.zcard(REDIS_KEY)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/client.py", line 2395, in zcard
    return self.execute_command('ZCARD', name)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 1059, in get_connection
    connection.connect()
  File "/usr/local/python3/lib/python3.6/site-packages/redis/connection.py", line 531, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 110 connecting to 120.79.34.216:6379. Connection timed out.

**Comment by jeeshv** [comment]
原因是没有安装、部署到虚拟环境
