### ISSUE TITLE
弹出错误，请求帮助attributes() got an unexpected keyword argument 'frozen'

### ISSUE THREAD

**Issue by ZhengPhilip** [Python3WebSpider/ProxyPool#7]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3\project\ProxyPool-master\run.py", line 1, in <module>
    from proxypool.scheduler import Scheduler
  File "D:\Anaconda3\envs\py3\project\ProxyPool-master\proxypool\scheduler.py", line 4, in <module>
    from proxypool.getter import Getter
  File "D:\Anaconda3\envs\py3\project\ProxyPool-master\proxypool\getter.py", line 1, in <module>
    from proxypool.tester import Tester
  File "D:\Anaconda3\envs\py3\project\ProxyPool-master\proxypool\tester.py", line 2, in <module>
    import aiohttp
  File "D:\Anaconda3\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "D:\Anaconda3\lib\site-packages\aiohttp\client.py", line 16, in <module>
    from . import client_exceptions, client_reqrep
  File "D:\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 18, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "D:\Anaconda3\lib\site-packages\aiohttp\helpers.py", line 161, in <module>
    @attr.s(frozen=True, slots=True)
TypeError: attributes() got an unexpected keyword argument 'frozen'

**Comment by ZhengPhilip** [comment]
emmm，更新aiohttp后就好了……
