### ISSUE TITLE
一个redis的问题

### ISSUE THREAD

**Issue by winturn** [Python3WebSpider/ProxyPool#80]
```
2020-07-13 09:44:06.589 | ERROR    | proxypool.scheduler:run_getter:48 - An error has been caught in function 'run_getter', process 'MainProcess' (8
), thread 'MainThread' (140094845962048):
Traceback (most recent call last):

  File "run.py", line 12, in <module>
    getattr(Scheduler(), f'run_{args.processor}')()
            └ <class 'proxypool.scheduler.Scheduler'>

> File "/app/proxypool/scheduler.py", line 48, in run_getter
    getter.run()
    │      └ <function Getter.run at 0x7f6a5e91a6a8>
    └ <proxypool.processors.getter.Getter object at 0x7f6a5bfb5e80>

  File "/app/proxypool/processors/getter.py", line 38, in run
    self.redis.add(proxy)
    │    │     │   └ Proxy(host='60.179.200.202', port=8720)
    │    │     └ <function RedisClient.add at 0x7f6a5df20d90>
    │    └ <proxypool.storages.redis.RedisClient object at 0x7f6a5bfb5f28>
    └ <proxypool.processors.getter.Getter object at 0x7f6a5bfb5e80>

  File "/app/proxypool/storages/redis.py", line 42, in add
           │    │  │    │          │      │     └ <function Proxy.string at 0x7f6a5e031510>
           │    │  │    │          │      └ Proxy(host='60.179.200.202', port=8720)
           │    │  │    │          └ 10
           │    │  │    └ 'proxies:universal'
           │    │  └ <function StrictRedis.zadd at 0x7f6a5e116400>
           │    └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
           └ <proxypool.storages.redis.RedisClient object at 0x7f6a5bfb5f28>

  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1697, in zadd
    return self.execute_command('ZADD', name, *pieces)
           │    │                       │      └ [10, '60.179.200.202:8720']
           │    │                       └ 'proxies:universal'
           │    └ <function StrictRedis.execute_command at 0x7f6a5e10ef28>
           └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
           │    │              │           │               └ {}
           │    │              │           └ 'ZADD'
           │    │              └ Connection<host=redis,port=6379,db=0>
           │    └ <function StrictRedis.parse_response at 0x7f6a5e112048>
           └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
               │          └ <function Connection.read_response at 0x7f6a5e109c80>
               └ Connection<host=redis,port=6379,db=0>
    raise response
          └ ReadOnlyError("You can't write against a read only replica.",)

redis.exceptions.ReadOnlyError: You can't write against a read only replica.

```

**Comment by Germey** [comment]
用错链接了吧，你用了一个只读的 redis 链接。

**Comment by Germey** [comment]
Redis 怎么搭建的？连的 slave？

**Comment by winturn** [comment]
用docker连接的

**Comment by winturn** [comment]
既然没有其他用户反馈该问题，那也有可能是我自身原因。
前几天我的服务器有个报警，
```检测到存在未处理的 /var/lib/docker/overlay2/7af0cb608e2d88241efb45d851c315cdae7a504d0d7b5ff2331d4a9e2c45b971/merged/tmp/red2.so 木马文件```
可能和这个有关系吧。

如果以后再发现这个问题再解决吧。
