### ISSUE TITLE
另一个redis的问题

### ISSUE THREAD

**Issue by winturn** [Python3WebSpider/ProxyPool#81]
```
2020-07-13 20:33:25.168 | ERROR    | proxypool.scheduler:run_getter:48 - An error has been caught in function 'run_getter', process 'MainProcess' (8
), thread 'MainThread' (140094845962048):
Traceback (most recent call last):

  File "run.py", line 12, in <module>
    getattr(Scheduler(), f'run_{args.processor}')()
            └ <class 'proxypool.scheduler.Scheduler'>

> File "/app/proxypool/scheduler.py", line 48, in run_getter
    getter.run()
    │      └ <function Getter.run at 0x7f6a5e91a6a8>
    └ <proxypool.processors.getter.Getter object at 0x7f6a5bfb5e80>

  File "/app/proxypool/processors/getter.py", line 38, in run
    self.redis.add(proxy)
    │    │     │   └ Proxy(host='60.179.201.207', port=8647)
    │    │     └ <function RedisClient.add at 0x7f6a5df20d90>
    │    └ <proxypool.storages.redis.RedisClient object at 0x7f6a5bfb5f28>
    └ <proxypool.processors.getter.Getter object at 0x7f6a5bfb5e80>
  File "/app/proxypool/storages/redis.py", line 42, in add
    return self.db.zadd(REDIS_KEY, score, proxy.string())
           │    │  │    │          │      │     └ <function Proxy.string at 0x7f6a5e031510>
           │    │  │    │          │      └ Proxy(host='60.179.201.207', port=8647)
           │    │  │    │          └ 10
           │    │  │    └ 'proxies:universal'
           │    │  └ <function StrictRedis.zadd at 0x7f6a5e116400>
           │    └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
           └ <proxypool.storages.redis.RedisClient object at 0x7f6a5bfb5f28>

  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1697, in zadd
    return self.execute_command('ZADD', name, *pieces)
           │    │                       │      └ [10, '60.179.201.207:8647']
           │    │                       └ 'proxies:universal'
           │    └ <function StrictRedis.execute_command at 0x7f6a5e10ef28>
           └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
           │    │              │           │               └ {}
           │    │              │           └ 'ZADD'
           │    │              └ Connection<host=redis,port=6379,db=0>
           │    └ <function StrictRedis.parse_response at 0x7f6a5e112048>
           └ StrictRedis<ConnectionPool<Connection<host=redis,port=6379,db=0>>>
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
               └ Connection<host=redis,port=6379,db=0>
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
          └ ResponseError('MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands t...

redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

```

**Comment by winturn** [comment]
既然没有其他用户反馈该问题，那也有可能是我自身原因。
前几天我的服务器有个报警，
```检测到存在未处理的 /var/lib/docker/overlay2/7af0cb608e2d88241efb45d851c315cdae7a504d0d7b5ff2331d4a9e2c45b971/merged/tmp/red2.so 木马文件```
可能和这个有关系吧。

如果以后再发现这个问题再解决吧。
